# group_vars/ws1_gamecenter.yml
---
# Variables de conexión a ESXi (WS1)
esxi_hostname: '172.17.25.18'
esxi_username: 'root'
esxi_password: 'qwe123$'
datastore: 'datastore1' # Cambia esto si tu datastore tiene otro nombre

# Variables de la red Game Center
vswitch_internal_name: 'vSwitch_Game_LAN'
network_internal_name: 'LAN_Game_Center'
network_internal_subnet: '192.168.1.0'
network_internal_netmask: '255.255.255.0'
network_internal_gateway: '192.168.1.1'

# Definición de las Máquinas Virtuales para WS1
vms_to_create:
  - name: 'VM-Router-Game'
    template: 'ubuntu-server-template'
    cpu: 1
    memory_mb: 1024
    disk_size_gb: 20
    networks:
      - name: 'VM Network' # Red de gestión conectada a la red 192.17.25.0/24
        type: 'dhcp'
      - name: '{{ network_internal_name }}' # Red interna del Game Center
        type: 'static'
        ip: '192.168.1.1'
        netmask: '255.255.255.0'

  - name: 'VM-FOG-Server-Game'
    template: 'ubuntu-server-template'
    cpu: 2
    memory_mb: 4096
    disk_size_gb: 100
    networks:
      - name: '{{ network_internal_name }}'
        type: 'dhcp'

  - name: 'VM-Cliente-01-Game'
    template: 'ubuntu-server-template' # Usarías una plantilla de Windows según el PDF
    cpu: 4
    memory_mb: 8192
    disk_size_gb: 150
    networks:
      - name: '{{ network_internal_name }}'
        type: 'dhcp'