---
- name: Aplicar configuración a los servidores del Game Center
  hosts: fog_servers_gamecenter
  become: true
  roles:
    - role: common
    - role: manage_users
    - role: install_fog

- name: Aplicar configuración a los servidores del Laboratorio Académico
  hosts: fog_servers_academic
  become: true
  roles:
    - role: common
    - role: manage_users
    - role: install_fog