---
# roles/configure_linux_clients/tasks/main.yml
- name: "Clientes Linux | Instalar software acad√©mico"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ academic_software_to_install }}"