---
- name: Instalar software acad√©mico con APT
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
  loop: "{{ academic_software_to_install }}"
  become: true