---
# Credenciales para ESXi
esxi_user: root

# Credenciales para DENTRO de las VMs (para que VMware Tools ejecute comandos)
# Asumimos que todas las VMs Linux tienen el mismo usuario 'root' y contrase√±a
vm_guest_admin_user: root