---
# Usuario que usas para conectarte/administrar
ansible_user: server-almalinux-aguilar

# Contrase√±a Sudo (se toma del vault)
#ansible_become_password: "{{ vault_sudo_password }}"

ansible_become_password: "qwe123$"
ansible_python_interpreter: /usr/bin/python3