---
common_packages:
  - git
  - htop
  - firewalld
  - fail2ban

users_to_manage:
  - { name: 'franco-gc', state: 'present', groups: 'wheel' }
  - { name: 'rodrigo-gc', state: 'present', groups: 'wheel' }

# Discos extra a formatear y montar
storage_volumes_to_manage:
  - { device: '/dev/sdb', fstype: 'ext4', path: '/mnt/fog_images' }