---
# Lista de VMs de Linux Mint en WS2
vms_clients_ws1:
  - "Cliente-LinuxMint-Aguilar"

# Software acad√©mico a instalar (usa nombres de apt)
academic_software_to_install:
  - "code"        # (Visual Studio Code)
  - "gimp"
  - "libreoffice"