---
# --- Configuración de Conexión para Windows ---

# Usuario administrador en tus VMs cliente de Windows
ansible_user: Cliente-Win11-Home
ansible_become_password: "qwe123$"

# Usar WinRM (protocolo de Windows) en lugar de SSH
ansible_connection: winrm

# Ajustes de WinRM (necesarios para la mayoría de las conexiones)
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: ntlm